
<div class="content-item create_form_box" data-name="创建表单">
    <div class=" form_title">
        <a>|&nbsp;创建表单</a>
    </div>
    <div class="form_content_box">
        <div class="form">
            <div class="control_title">
                <div class="control_btn">控件</div>
            </div>
            <div class="control_form">
                <div class="form_btn_box">
                    <div class="form-item yuansu" data-type="single"><i class="fa fa-pencil"></i>单行输入框</div>
                    <div class="form-item yuansu" data-type="multi"><i class="fa fa-edit"></i>多行输入框</div>
                    <div class="form-item yuansu" data-type="radio"><i class="fa fa-circle"></i>单选框</div>
                    <div class="form-item yuansu" data-type="checkbox"><i class="fa fa-check-square"></i>多选框</div>
                    <div class="form-item yuansu" data-type="select"><i class="fa fa-arrow-circle-down"></i>下拉框</div>
                    <div class="form-item yuansu" data-type="file"><i class="fa fa-paperclip"></i>附件</div>
                    <div class="form-item yuansu" data-type="date"><i class="fa fa-calendar"></i>日期</div>
                    <div class="explain">说明：环境、位置不能存在多个</div>
                    <div class="refer">保存</div>
                </div>
            </div>
        </div>
        <div class="phone">
            <div id="p_container" class="right-panel"></div>
        </div>
        <div class="set">
            <div class="control_title ">
                <div class="control_btn right_btn">控件设计</div>
            </div>
            <div class="control_form toastinfo"></div>
        </div>
    </div>
</div>

<div style="display:none" id="publish">
    <!-- 发布 -->
    <div class="pub_title">
        <span class="pub_head">发布</span>
        <div class="pub_hr"></div>
    </div>
    <!-- 发布方式 -->
    <div class="pub_content">
        <div class="pub_con_title">
            <p>| 发布方式</p>
        </div>
        <form class="pub_form">
            表单名称 &nbsp; &nbsp;
            <input type="text" class="pub_for_input form_name input-text" placeholder="请输入表单名称">
            <span class="pub_active_red">*</span>
            <br>
            <p class="pub_add_person">
                分配表单查看人员
                <button class="pub_button">添加人员</button>
            </p>
            <p class="pub_add_person">
                <span>分配表单管理人员</span>
                <button class="pub_button">添加人员</button>
            </p>
        </form>
    </div>
    <!-- 启用和使用 -->
    <div class="pub_content">
        <div class="pub_con_title">
            <p>| 启用和使用</p>
        </div>
        <form class="pub_form">
            定时启停表单 &nbsp;
            <input type="checkbox" class="start start_datetime"><br>
            <div id="datetime_control" style="display: none;">
                <input type="datetime-local" class="start_time">至<input type="datetime-local" class="end_time">
            </div>
            <br> 收集定量反馈后停用表单 &nbsp;
            <input type="checkbox" class="stop stop_datetime">
        </form>
        <script>
            $(".start_datetime").on('click',function(){
                var checked = $(this).prop("checked");
                if(checked){
                    $("#datetime_control").show();
                }
                else{
                    $("#datetime_control").hide();
                }
            });
        </script>
    </div>
    <!-- 提交和通知 -->
    <div class="pub_content">
        <div class="pub_con_title">
            <p>| 提交和通知</p>
        </div>
        <form class="pub_form">
            表单提交后页面显示 &nbsp;
            <br>
            <p>
                <span>表单提交后文字说明 &nbsp;</span>
                <textarea placeholder="谢谢参与" class="pub_con_area from-word"></textarea>
            </p>
        </form>
    </div>
    <!-- 填写控制 -->
    <div class="pub_footer">
        <button class="pub_button"  id="submit">保存并使用</button>
        <button class="pub_button">保存</button>
    </div>
</div>
<script>
	$(".userNa").text('<?=$name?>')
</script>