<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>数据侠信息采集系统</title>
    <!-- FontAwsome -->
    <link rel="stylesheet" href="/source/font-awesome-4.7.0/css/font-awesome.min.css">
    <!-- ZTree -->
    <link rel="stylesheet" href="/css/zTreeStyle.css">
    <!-- bootstrap -->
    <link rel="stylesheet" href="/source/bootstrapt/bootstrap.css" media="all">
    <!-- layui -->
    <link rel="stylesheet" href="/source/layui/css/layui.css" media="all">
    <!-- 主要样式 -->
    <link rel="stylesheet" href="/css/index.css">
    <link rel="stylesheet" href="/css/createform.css">
    <script src="/js/jquery-3.3.1.min.js"></script>
    <script src="/source/layui/layui.js"></script>
    <script src="/js/formpage.js"></script>

</head>
<body>
<!-- 头部header部分 -->
<header class="top">
    <h2>数据侠信息采集系统</h2>
    <div class="welcome">
        <!-- <p class="return"><a href="">返回应用中心</a></p> -->
        <div class="user">
            <img src="/images/user.png">
            <span><span class="userNa"></span>，欢迎访问本系统！</span>
        </div>
    </div>
</header>
<div id="content">
    <!-- 左边的菜单操作部分 -->
    <div id="content_left">
        <div class="menu tab_style">
            <img src="/images/menu.png" width="18px" height="18px">
            <span>操作菜单</span>
        </div>
        <div class="menu_list">
            <div class="list_item">
                <div class="menu_title tab_style">
                    <img src="/images/form.png">
                    <span>表单设置</span>
                </div>
                <ul class="list_child" id="formList">
                </ul>
            </div>
            <div class="list_item">
                <div class="menu_title tab_style">
                    <img src="/images/setting.png">
                    <span>系统设置</span>
                </div>
                <ul class="list_child" id="systemList">
                </ul>
            </div>
        </div>
    </div>
    <!-- 右边内容显示部分 -->
    <div id="content_right">
        <!-- 面包屑导航部分 -->
        <div class="nav_bar">
            <ul class="nav_crumbs">
                <li class="loc">位置：</li>
                <li class="title_first"></li>
                <li class="title_second"></li>
                <li class="title_third" style="display:none">&nbsp;>发布</li>
            </ul>
        </div>
        <div class="content-box">
            <?=$this->content?>
        </div>
    </div>

</div>

<footer class="bottom">
    <img src="/images/notice.png">
    <span>数据侠信息采集系统</span>
</footer>

<script src="/source/bootstrapt/bootstrap.js"></script>
<!-- Ztree -->
<script src="/js/jquery.ztree.all.min.js"></script>
<!-- 主要样式 -->
<script src="/js/index.js"></script>
<!-- 创建表单 -->
<script src="/js/move.js"></script>
<!-- 日志查询 -->
<script src="/js/logManage.js"></script>
<!-- bootstrap -->
<script src="/source/bootstrapt/bootstrap.js"></script>
</body>
</html>

