<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta http-equiv="Expires" content="0">
    <title>信息采集</title>
    <link href="/css/login.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div class="login_box">
    <div class="login_l_img"><img src="/images/login-img.png" /></div>
    <div class="login">
        <div class="login_logo"><a href="#"><img src="/images/login_logo.png" /></a></div>
        <div class="login_name">
            <p>信息采集系统</p>
        </div>
        <form>
            <input name="username" type="text" placeholder="用户名">
            <input name="password" type="password" id="password" placeholder="密码" />
            <input value="登录" style="width:100%;" type="button" id="submit">
        </form>
    </div>
</div>
<script src="/js/jquery-3.3.1.min.js"></script>
<script src="/source/layui/layui.js"></script>
<script>
	//导入layer模块
	layui.use('layer',function(){
		var layer = layui.layer;
	});

    $("#submit").on("click", function () {
        if ($("input").eq(0).val() == '' || $("input").eq(0).val() == "用户名") {
            layer.msg("用户名不能为空",{icon:2});
            $("input").eq(0).focus();
        } else if ($("input").eq(1).val() == '') {
	        layer.msg("密码不能为空",{icon:2});
            $("input").eq(1).focus().focus();
        } else {
            var username = $("input").eq(0).val();
            var psd = $('input').eq(1).val();
            $.ajax({
                url: "/application/index/login",
                type: 'post',
                data: {
                    name: username,
                    pass: psd
                },
                success: function (e) {
                    console.log(e);
                    if(e.code === 0){
                        location.href = "/application/myform";
                    }
                    else{
	                    layer.msg(e.msg,{icon:2});
                    }
                },
                error:function(){
	                layer.msg("不可预知的错误",{icon:2});
                }
            })
        }
    });
</script>
</body>
</html>