
    
<?php echo $name?>

<div class="content-item" data-name='我的表单' style="display:block">
    <div class="wdbd_box">
        <div class="wdbs_name">
            <div>表单名称：</div><input type="text" placeholder="请输入表单名称" class="wdbd_text">
            <div class="wdbd-a">创建时间 </div>&nbsp;<input type="text" class="wdbd_text createtime">
            <div>至</div> &nbsp;<input type="text" class="wdbd_text arrivetime">
            <input type="button" value="查询" class="wdbd_button wdbd_sercher">
            <input type="button" value="重置" class="wdbd_button wdbd_reset">
        </div>
        <div class="wdbs_name">
            分&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;类：
            <input type="button" value="全部" class="wdbd_button wdbd_all">
            <input type="button" value="未分类" class="wdbd_button wdbd_noclass">
            <div type="button" class=" wdbd_edit">
                <i class="layui-icon">&#xe642;</i>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-md-6 col-lg-4 bd_content_margin">
                    <div class="wdbd_content">
                        <div class="wdbd_add">
                            <i class="layui-icon " style="font-size: 80px; color: #999999;">&#xe654;</i>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-6 col-lg-4 bd_content_margin" data-id="${res[0][i].id}"
                     data-name="我的表单">
                    <div class="wdbd_content ">
                        <div class="wdbd_content_head">
                            <div class="wdbd_content_head_title">
                                <span class="wdbd_content_title">人口</span>
                                <div class="wdbd_content_progress">正在收集</div>
                                <span class="wdbd_content_delete"><i class="layui-icon" style="font-size:26px;">&#xe640;</i></span>
                            </div>
                            <div class="wdbd_content_time">创建时间：<span class="create_time">2018-01-01
                                                    13：00</span></div>
                        </div>
                        <div class="wdbd_content_bottom wdbd-bottom">
                            <div class="wdbd_content_information">
                                <div class="wdbd_content_num">115</div>
                                <div class="wdbd_content_ecplain">已采集数据</div>
                            </div>
                            <div class="wdbd_content_information">
                                <div class="wdbd_content_num">32</div>
                                <div>今日新增</div>
                            </div>
                            <div class="wdbd_content_information">
                                <div class="wdbd_content_num">213</div>
                                <div>表单浏览量</div>
                            </div>
                            <div class="wdbd_content_operation ">
                                <div class="wdbd_content_icon bd-copy"> <img src="/images/u3.png"></div>
                                <div class="wdbd_content_icon  bd-choosecolor">
                                    <img src="/images/u1.png">
                                    <div class="wdbd_content_icon choosecolor"></div>
                                </div>
                                <div class="wdbd_content_icon bd-see"> <img src="/images/u4.png"></div>
                                <div class="wdbd_content_icon bd-class"> <img src="/images/u2.png"></div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-6 col-lg-4 bd_content_margin" data-id="${res[0][i].id}"
                     data-name="我的表单">
                    <div class="wdbd_content ">
                        <div class="wdbd_content_head">
                            <div class="wdbd_content_head_title">
                                <span class="wdbd_content_title">户籍</span>
                                <div class="wdbd_content_progress">暂停中</div>
                                <span class="wdbd_content_delete"><i class="layui-icon" style="font-size:26px;">&#xe640;</i></span>
                            </div>
                            <div class="wdbd_content_time">创建时间：<span class="create_time">2018-01-01
                                                    13：00</span></div>
                        </div>
                        <div class="wdbd_content_bottom wdbd-bottom">
                            <div class="wdbd_content_information">
                                <div class="wdbd_content_num">115</div>
                                <div class="wdbd_content_ecplain">已采集数据</div>
                            </div>
                            <div class="wdbd_content_information">
                                <div class="wdbd_content_num">32</div>
                                <div>今日新增</div>
                            </div>
                            <div class="wdbd_content_information">
                                <div class="wdbd_content_num">213</div>
                                <div>表单浏览量</div>
                            </div>
                            <div class="wdbd_content_operation ">
                                <div class="wdbd_content_icon bd-copy"> <img src="/images/u3.png"></div>
                                <div class="wdbd_content_icon  bd-choosecolor">
                                    <img src="/images/u1.png">
                                    <div class="wdbd_content_icon choosecolor"></div>
                                </div>
                                <div class="wdbd_content_icon bd-see"> <img src="/images/u4.png"></div>
                                <div class="wdbd_content_icon bd-class"> <img src="/images/u2.png"></div>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>